import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export default function TermsPage() {
  return (
    <main className="min-h-screen px-4 py-16 sm:py-20 bg-gradient-to-b from-blue-50 via-white to-blue-50/50 relative overflow-hidden">
      <div aria-hidden className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -top-28 -left-28 h-80 w-80 rounded-full bg-blue-300/30 blur-3xl" />
        <div className="absolute -bottom-28 -right-28 h-80 w-80 rounded-full bg-blue-400/30 blur-3xl" />
      </div>

      <div className="relative max-w-4xl mx-auto">
        <div className="text-center mb-10">
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-3 bg-gradient-to-r from-blue-600 to-blue-800 bg-clip-text text-transparent pb-3">
            Terms of Service
          </h1>
          <p className="text-lg text-blue-800/90">
            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
          </p>
        </div>

        <Card className="border-2 border-blue-200/50 shadow-xl rounded-2xl bg-white/70 backdrop-blur-md">
          <CardHeader>
            <CardTitle className="text-2xl text-blue-900">ultrafastutilities Terms of Service</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 text-blue-900/90">
            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">1. Acceptance of Terms</h2>
              <p className="text-sm leading-relaxed">
                By accessing and using ultrafastutilities, you accept and agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use our service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">2. Description of Service</h2>
              <p className="text-sm leading-relaxed">
                ultrafastutilities provides an automated document generation service that creates privacy policies, 
                terms of service, and cookie policies based on information you provide. The generated documents are 
                templates and should be reviewed and customized for your specific needs.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">3. Not Legal Advice</h2>
              <p className="text-sm leading-relaxed">
                <strong>Important:</strong> The documents generated by our service are templates and do not constitute 
                legal advice. We are not a law firm and do not provide legal services. You should consult with a qualified 
                attorney for legal advice specific to your situation. We make no warranties about the legal sufficiency 
                of the generated documents.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">4. User Responsibilities</h2>
              <p className="text-sm leading-relaxed mb-2">
                You agree to:
              </p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4">
                <li>Provide accurate and complete information when using our service</li>
                <li>Review and customize generated documents before use</li>
                <li>Consult with legal professionals as needed</li>
                <li>Use the generated documents in compliance with applicable laws</li>
                <li>Not use our service for any illegal or unauthorized purpose</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">5. Payment and Refunds</h2>
              <p className="text-sm leading-relaxed">
                Premium features require a one-time payment of $4.99. Payments are processed securely through Paddle. 
                Due to the digital nature of our service, all sales are final. Refunds may be considered on a case-by-case 
                basis for technical issues that prevent service delivery.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">6. Intellectual Property</h2>
              <p className="text-sm leading-relaxed">
                The documents you generate using our service are yours to use, modify, and distribute as you see fit. 
                However, the underlying templates, algorithms, and service design remain the property of ultrafastutilities.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">7. Limitation of Liability</h2>
              <p className="text-sm leading-relaxed">
                To the maximum extent permitted by law, ultrafastutilities shall not be liable for any indirect, 
                incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether 
                incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting 
                from your use of our service.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">8. Disclaimer of Warranties</h2>
              <p className="text-sm leading-relaxed">
                Our service is provided "as is" and "as available" without warranties of any kind, either express or 
                implied. We do not warrant that the service will be uninterrupted, secure, or error-free.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">9. Indemnification</h2>
              <p className="text-sm leading-relaxed">
                You agree to indemnify and hold harmless ultrafastutilities, its officers, directors, employees, and 
                agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from 
                your use of the service or violation of these terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">10. Changes to Terms</h2>
              <p className="text-sm leading-relaxed">
                We reserve the right to modify these terms at any time. We will notify users of significant changes by 
                posting the updated terms on this page and updating the "Last updated" date.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">11. Termination</h2>
              <p className="text-sm leading-relaxed">
                We may terminate or suspend your access to our service immediately, without prior notice, for any reason, 
                including if you breach these terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">12. Governing Law</h2>
              <p className="text-sm leading-relaxed">
                These terms shall be governed by and construed in accordance with applicable laws, without regard to 
                conflict of law provisions.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">13. Contact Information</h2>
              <p className="text-sm leading-relaxed">
                If you have questions about these terms, please contact us at: 
                <a href="mailto:support@ultrafastutilities.com" className="text-blue-600 hover:underline ml-1">
                  support@ultrafastutilities.com
                </a>
              </p>
            </div>
          </CardContent>
        </Card>

        <div className="mt-8 text-center">
          <Link href="/generate">
            <Button className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30">
              Generate Your Policy Now
            </Button>
          </Link>
        </div>
      </div>
    </main>
  );
}
