import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import SeoIntro from "@/components/SeoIntro";

export const metadata: Metadata = {
  title: "Terms of Service, Privacy Policy & Refund Policy | ultrafastutilities",
  description: "Terms of Service, Privacy Policy, and Refund Policy for ultrafastutilities. All policies in one place for Dodo verification.",
  robots: {
    index: true,
    follow: true,
  },
};

export default function TermsPage() {
  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const businessName = "ultrafastutilities";
  const contactEmail = "anuformal@gmail.com";

  return (
    <main className="min-h-screen px-4 py-16 sm:py-20 bg-gradient-to-b from-blue-50 via-white to-blue-50/50 relative overflow-hidden">
      <div aria-hidden className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -top-28 -left-28 h-80 w-80 rounded-full bg-blue-300/30 blur-3xl" />
        <div className="absolute -bottom-28 -right-28 h-80 w-80 rounded-full bg-blue-400/30 blur-3xl" />
      </div>

      <SeoIntro
        title="Terms of Service, Privacy Policy and Refund Policy"
        description="Review the terms, privacy practices, and refund policy for ultrafastutilities."
      />

      <div className="relative max-w-4xl mx-auto">

        {/* Terms of Service Section */}
        <Card className="border-2 border-blue-200/50 shadow-xl rounded-2xl bg-white/70 backdrop-blur-md mb-8">
          <CardHeader>
            <CardTitle className="text-2xl text-blue-900">TERMS OF SERVICE</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 text-blue-900/90">
            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">1. Acceptance of Terms</h2>
              <p className="text-sm leading-relaxed">
                By accessing and using {businessName} (the "Service"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by the above, please do not use this Service.
              </p>
              <p className="text-sm leading-relaxed mt-2">
                These Terms of Service ("Terms") constitute a legally binding agreement between you and {businessName} ("we," "our," or "us"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">2. Description of Service</h2>
              <p className="text-sm leading-relaxed">
                {businessName} provides an automated document generation service that creates privacy policies, terms of service, and cookie policies based on information you provide. We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time, with or without notice.
              </p>
              <div className="mt-3">
                <h3 className="text-lg font-semibold mb-2 text-blue-900">2.1 Digital Document Purchase</h3>
                <p className="text-sm leading-relaxed">
                  When you purchase digital documents through our Service, you are purchasing a license to use the generated documents for your business purposes. The documents are provided as digital files that you can download, modify, and use in accordance with these Terms.
                </p>
              </div>
              <div className="mt-3">
                <h3 className="text-lg font-semibold mb-2 text-blue-900">2.2 No Legal Advice</h3>
                <p className="text-sm leading-relaxed">
                  The documents generated by our Service are templates and do not constitute legal advice. We are not a law firm, and our Service does not provide legal services. The documents are provided "as is" for informational purposes only. You should consult with a qualified legal professional to ensure the documents meet your specific legal requirements and business needs.
                </p>
              </div>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">3. User Responsibilities</h2>
              <p className="text-sm leading-relaxed mb-2">You agree to:</p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4">
                <li>Provide accurate, current, and complete information when using our service</li>
                <li>Review and customize generated documents before use</li>
                <li>Consult with legal professionals as needed</li>
                <li>Use the generated documents in compliance with applicable laws</li>
                <li>Not use our service for any illegal or unauthorized purpose</li>
                <li>Maintain the security of your account credentials</li>
                <li>Accept all responsibility for activities that occur under your account</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">4. User Conduct</h2>
              <p className="text-sm leading-relaxed mb-2">You agree not to use the Service to:</p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4">
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe upon the rights of others</li>
                <li>Transmit any harmful, offensive, or illegal content</li>
                <li>Interfere with or disrupt the Service or servers</li>
                <li>Attempt to gain unauthorized access to any portion of the Service</li>
                <li>Use automated systems (bots, scrapers) to access the Service without permission</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">5. Intellectual Property</h2>
              <p className="text-sm leading-relaxed">
                All content, features, and functionality of the Service, including but not limited to text, graphics, logos, icons, images, and software, are the exclusive property of {businessName} or its content suppliers and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.
              </p>
              <p className="text-sm leading-relaxed mt-2">
                The documents you generate using our service are yours to use, modify, and distribute as you see fit. However, the underlying templates, algorithms, and service design remain the property of {businessName}.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">6. Disclaimer of Warranties</h2>
              <p className="text-sm leading-relaxed">
                THE MATERIALS ON {businessName.toUpperCase()} ARE PROVIDED ON AN 'AS IS' BASIS. {businessName.toUpperCase()} MAKES NO WARRANTIES, EXPRESSED OR IMPLIED, AND HEREBY DISCLAIMS AND NEGATES ALL OTHER WARRANTIES INCLUDING, WITHOUT LIMITATION:
              </p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4 mt-2">
                <li>Implied warranties or conditions of merchantability</li>
                <li>Fitness for a particular purpose</li>
                <li>Non-infringement of intellectual property or other violation of rights</li>
                <li>Accuracy, reliability, or completeness of content</li>
                <li>Uninterrupted or error-free operation</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">7. Limitation of Liability</h2>
              <p className="text-sm leading-relaxed">
                IN NO EVENT SHALL {businessName.toUpperCase()} OR ITS SUPPLIERS, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF DATA OR PROFIT, OR DUE TO BUSINESS INTERRUPTION) ARISING OUT OF THE USE OR INABILITY TO USE THE MATERIALS ON {businessName.toUpperCase()}, EVEN IF {businessName} OR AN AUTHORIZED REPRESENTATIVE HAS BEEN NOTIFIED ORALLY OR IN WRITING OF THE POSSIBILITY OF SUCH DAMAGE.
              </p>
              <p className="text-sm leading-relaxed mt-2">
                Some jurisdictions do not allow limitations on implied warranties or limitations of liability for incidental or consequential damages, so these limitations may not apply to you.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">8. Indemnification</h2>
              <p className="text-sm leading-relaxed">
                You agree to indemnify, defend, and hold harmless {businessName}, its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from your use of and access to the Service, your violation of any term of these Terms, or your violation of any third-party right.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">9. Modifications to Terms</h2>
              <p className="text-sm leading-relaxed">
                {businessName} may revise these Terms of Service at any time without notice. By using this Service, you are agreeing to be bound by the then current version of these Terms of Service. We will notify you of any material changes by posting the new Terms of Service on this page and updating the "Last updated" date.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">10. Termination</h2>
              <p className="text-sm leading-relaxed">
                We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">11. Governing Law</h2>
              <p className="text-sm leading-relaxed">
                These Terms and Conditions are governed by and construed in accordance with applicable laws, without regard to conflict of law provisions. Any disputes arising out of or relating to these Terms or the Service shall be resolved through appropriate legal channels.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Privacy Policy Section */}
        <Card className="border-2 border-blue-200/50 shadow-xl rounded-2xl bg-white/70 backdrop-blur-md mb-8">
          <CardHeader>
            <CardTitle className="text-2xl text-blue-900">PRIVACY POLICY</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 text-blue-900/90">
            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">1. Information We Collect</h2>
              <p className="text-sm leading-relaxed">
                We collect information that you provide directly to us when you use our Service, including:
              </p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4 mt-2">
                <li>Information you provide when creating an account (name, email address)</li>
                <li>Information you provide when using our document generation service (business details, website information)</li>
                <li>Payment information processed securely through Dodo (we do not store payment card details)</li>
                <li>Communications you send to us (support requests, feedback)</li>
              </ul>
              <p className="text-sm leading-relaxed mt-2">
                We also automatically collect certain information when you use our Service, including:
              </p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4 mt-2">
                <li>Log data (IP address, browser type, pages visited, time spent on pages)</li>
                <li>Device information (device type, operating system)</li>
                <li>Cookies and similar tracking technologies (see Cookie Policy section)</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">2. How We Use Your Information</h2>
              <p className="text-sm leading-relaxed mb-2">We use the information we collect to:</p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4">
                <li>Provide, maintain, and improve our Service</li>
                <li>Process your transactions and send you related information</li>
                <li>Send you technical notices, updates, and support messages</li>
                <li>Respond to your comments, questions, and requests</li>
                <li>Monitor and analyze trends, usage, and activities</li>
                <li>Detect, prevent, and address technical issues and fraud</li>
                <li>Comply with legal obligations</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">3. Information Sharing and Disclosure</h2>
              <p className="text-sm leading-relaxed">
                We do not sell, trade, or rent your personal information to third parties. We may share your information only in the following circumstances:
              </p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4 mt-2">
                <li><strong>Service Providers:</strong> We may share information with third-party service providers who perform services on our behalf, such as payment processing (Dodo), hosting, analytics, and customer support.</li>
                <li><strong>Legal Requirements:</strong> We may disclose information if required to do so by law or in response to valid requests by public authorities.</li>
                <li><strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction.</li>
                <li><strong>With Your Consent:</strong> We may share your information with your consent or at your direction.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">4. Data Security</h2>
              <p className="text-sm leading-relaxed">
                We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">5. Your Rights and Choices</h2>
              <p className="text-sm leading-relaxed mb-2">Depending on your location, you may have certain rights regarding your personal information, including:</p>
              <ul className="list-disc list-inside text-sm space-y-1 ml-4">
                <li><strong>Access:</strong> Request access to your personal information</li>
                <li><strong>Correction:</strong> Request correction of inaccurate information</li>
                <li><strong>Deletion:</strong> Request deletion of your personal information</li>
                <li><strong>Opt-out:</strong> Opt-out of certain data processing activities</li>
                <li><strong>Data Portability:</strong> Request a copy of your data in a portable format</li>
              </ul>
              <p className="text-sm leading-relaxed mt-2">
                To exercise these rights, please contact us at {contactEmail}. We will respond to your request within a reasonable timeframe and in accordance with applicable laws.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">6. Cookies and Tracking Technologies</h2>
              <p className="text-sm leading-relaxed">
                We use cookies and similar tracking technologies to collect and use personal information about you. For more information about our use of cookies, please see our Cookie Policy section below or visit our dedicated cookie policy page.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">7. Data Retention</h2>
              <p className="text-sm leading-relaxed">
                We retain your personal information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law. When we no longer need your personal information, we will securely delete or anonymize it.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">8. International Data Transfers</h2>
              <p className="text-sm leading-relaxed">
                Your information may be transferred to and processed in countries other than your country of residence. These countries may have data protection laws that are different from those in your country. We take appropriate safeguards to ensure that your personal information receives an adequate level of protection.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">9. Children's Privacy</h2>
              <p className="text-sm leading-relaxed">
                Our Service is not intended for children under the age of 13 (or the applicable age of consent in your jurisdiction). We do not knowingly collect personal information from children. If you believe we have collected information from a child, please contact us immediately.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">10. Changes to This Privacy Policy</h2>
              <p className="text-sm leading-relaxed">
                We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">11. Contact Us</h2>
              <p className="text-sm leading-relaxed">
                If you have any questions about this Privacy Policy, please contact us at: <a href={`mailto:${contactEmail}`} className="text-blue-600 hover:underline">{contactEmail}</a>
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Refund Policy Section */}
        <Card className="border-2 border-blue-200/50 shadow-xl rounded-2xl bg-white/70 backdrop-blur-md mb-8">
          <CardHeader>
            <CardTitle className="text-2xl text-blue-900">REFUND POLICY</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 text-blue-900/90">
            <div>
              <h2 className="text-xl font-semibold mb-3 text-blue-900">Refund Policy</h2>
              <p className="text-sm leading-relaxed">
                All sales are final. We do not offer refunds for purchases made through our Service.
              </p>
              <p className="text-sm leading-relaxed mt-2">
                This is a one-time digital product purchase that provides immediate access to our document generation service and premium features. Once you have completed your purchase and gained access to the Service, the transaction is considered complete.
              </p>
              <p className="text-sm leading-relaxed mt-2">
                Due to the digital nature of our product and the immediate access provided upon purchase, we are unable to offer refunds, exchanges, or cancellations. By completing your purchase, you acknowledge that you have read and understood this refund policy.
              </p>
              <p className="text-sm leading-relaxed mt-2">
                If you have any questions or concerns about your purchase, please contact us at {contactEmail} before completing your transaction.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Contact Information */}
        <Card className="border-2 border-blue-200/50 shadow-xl rounded-2xl bg-white/70 backdrop-blur-md">
          <CardHeader>
            <CardTitle className="text-2xl text-blue-900">Contact Information</CardTitle>
          </CardHeader>
          <CardContent className="text-blue-900/90">
            <p className="text-sm leading-relaxed">
              If you have any questions about these Terms of Service, Privacy Policy, or Refund Policy, please contact us:
            </p>
            <div className="mt-4 space-y-2">
              <p className="text-sm">
                <strong>Email:</strong> <a href={`mailto:${contactEmail}`} className="text-blue-600 hover:underline ml-2">{contactEmail}</a>
              </p>
            </div>
          </CardContent>
        </Card>

        <div className="mt-8 text-center">
          <Link href="/generate">
            <Button className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white shadow-lg shadow-blue-500/30">
              Generate Your Policy Now
            </Button>
          </Link>
        </div>
      </div>
    </main>
  );
}
