import { PolicyData } from "../types";

export function generateCookiePolicy(data: PolicyData): string {
  const {
    businessName,
    contactEmail,
    cookies
  } = data;

  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  let policy = `COOKIE POLICY

Effective Date: ${effectiveDate}

1. INTRODUCTION

This Cookie Policy explains how ${businessName} ("we," "our," or "us") uses cookies and similar tracking technologies when you visit our website.

2. WHAT ARE COOKIES

Cookies are small text files that are placed on your computer or mobile device when you visit a website. They are widely used to make websites work more efficiently and provide information to the owners of the site.

3. HOW WE USE COOKIES

`;

  if (cookies === "none") {
    policy += `We do not use cookies on our website.`;
  } else if (cookies === "essential") {
    policy += `We use only essential cookies that are strictly necessary for the website to function properly. These cookies cannot be disabled in our systems.`;
  } else if (cookies === "analytics") {
    policy += `We use analytics cookies to help us understand how visitors interact with our website. These cookies collect information about how you use our website, such as which pages you visit most often.`;
  } else if (cookies === "advertising") {
    policy += `We use advertising cookies to deliver personalized advertisements and track the effectiveness of our advertising campaigns.`;
  } else if (cookies === "all") {
    policy += `We use various types of cookies on our website:

- Essential Cookies: These are necessary for the website to function properly.
- Analytics Cookies: These help us understand how visitors use our website.
- Advertising Cookies: These are used to deliver personalized advertisements.`;
  }

  policy += `\n\n4. MANAGING COOKIES

You can control and manage cookies in various ways. Please keep in mind that removing or blocking cookies can impact your user experience and parts of our website may no longer be fully accessible.

Most browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer.

5. THIRD-PARTY COOKIES

In addition to our own cookies, we may also use various third-party cookies to report usage statistics of the Service and deliver advertisements on and through the Service.

6. CONTACT US

If you have any questions about our use of cookies, please contact us:

Email: ${contactEmail}

---

This Cookie Policy was generated by PolicyDraft.in`;

  return policy;
}
