import { PolicyData } from "../types";

export function generatePrivacyPolicy(data: PolicyData): string {
  const {
    businessName,
    contactEmail,
    websiteType,
    dataCollected,
    collectionMethods,
    dataUsage,
    thirdPartySharing,
    cookies,
    userRights,
    country,
    state
  } = data;

  const location = state ? `${state}, ${country}` : country;
  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  let policy = `PRIVACY POLICY

Effective Date: ${effectiveDate}

1. INTRODUCTION

${businessName} ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our ${websiteType === 'other' ? data.otherType : websiteType} (the "Service").

By using our Service, you agree to the collection and use of information in accordance with this policy.

2. INFORMATION WE COLLECT

We collect information that you provide directly to us and information that is automatically collected when you use our Service.

2.1 Information You Provide

We may collect the following personal information:`;

  if (dataCollected.includes("None of the above")) {
    policy += `\n\nWe do not collect any personal information from our users.`;
  } else {
    const dataList = dataCollected.filter(d => d !== "None of the above");
    dataList.forEach(item => {
      policy += `\n- ${item}`;
    });
  }

  policy += `\n\n2.2 How We Collect Information

We collect information through the following methods:`;

  collectionMethods.forEach(method => {
    policy += `\n- ${method}`;
  });

  policy += `\n\n3. HOW WE USE YOUR INFORMATION

We use the information we collect for the following purposes:`;

  dataUsage.forEach(usage => {
    policy += `\n- ${usage}`;
  });

  policy += `\n\n4. SHARING YOUR INFORMATION`;

  if (thirdPartySharing.includes("No sharing")) {
    policy += `\n\nWe do not share your personal information with any third parties.`;
  } else {
    policy += `\n\nWe may share your information with the following third parties:`;
    const parties = thirdPartySharing.filter(p => p !== "No sharing");
    parties.forEach(party => {
      policy += `\n- ${party}`;
    });
  }

  policy += `\n\n5. COOKIES AND TRACKING TECHNOLOGIES`;

  if (cookies === "none") {
    policy += `\n\nWe do not use cookies or similar tracking technologies on our Service.`;
  } else if (cookies === "essential") {
    policy += `\n\nWe use only essential cookies that are necessary for the Service to function properly.`;
  } else if (cookies === "analytics") {
    policy += `\n\nWe use analytics cookies to understand how visitors interact with our Service.`;
  } else if (cookies === "advertising") {
    policy += `\n\nWe use advertising cookies to deliver personalized advertisements.`;
  } else if (cookies === "all") {
    policy += `\n\nWe use various types of cookies including essential, analytics, and advertising cookies.`;
  }

  policy += `\n\n6. YOUR RIGHTS

You have the following rights regarding your personal information:`;

  userRights.forEach(right => {
    policy += `\n- Right to ${right.toLowerCase()}`;
  });

  policy += `\n\nTo exercise these rights, please contact us using the information provided in the Contact section below.

7. DATA SECURITY

We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the Internet or electronic storage is 100% secure.

8. CHILDREN'S PRIVACY

Our Service is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13.

9. CHANGES TO THIS PRIVACY POLICY

We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Effective Date" at the top.

10. CONTACT US

If you have any questions about this Privacy Policy, please contact us:

Email: ${contactEmail}
Location: ${location}

---

This Privacy Policy was generated by PolicyDraft.in`;

  return policy;
}
