import { PolicyData } from "../types";

export function generateTermsOfService(data: PolicyData): string {
  const {
    businessName,
    contactEmail,
    country,
    state
  } = data;

  const location = state ? `${state}, ${country}` : country;
  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `TERMS OF SERVICE

Effective Date: ${effectiveDate}

1. ACCEPTANCE OF TERMS

By accessing and using ${businessName} (the "Service"), you accept and agree to be bound by the terms and provision of this agreement.

2. USE LICENSE

Permission is granted to temporarily access the materials on ${businessName} for personal, non-commercial transitory viewing only.

3. DISCLAIMER

The materials on ${businessName} are provided on an 'as is' basis. ${businessName} makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.

4. LIMITATIONS

In no event shall ${businessName} or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on ${businessName}, even if ${businessName} or an authorized representative has been notified orally or in writing of the possibility of such damage.

5. ACCURACY OF MATERIALS

The materials appearing on ${businessName} could include technical, typographical, or photographic errors. ${businessName} does not warrant that any of the materials on its website are accurate, complete, or current.

6. LINKS

${businessName} has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site.

7. MODIFICATIONS

${businessName} may revise these terms of service at any time without notice. By using this Service you are agreeing to be bound by the then current version of these terms of service.

8. GOVERNING LAW

These terms and conditions are governed by and construed in accordance with the laws of ${location} and you irrevocably submit to the exclusive jurisdiction of the courts in that location.

9. CONTACT INFORMATION

If you have any questions about these Terms of Service, please contact us:

Email: ${contactEmail}
Location: ${location}

---

These Terms of Service were generated by PolicyDraft.in`;
}
