import { PolicyData } from "../types";

export function generateTermsOfService(data: PolicyData): string {
  const {
    businessName,
    contactEmail,
    country,
    state
  } = data;

  const location = state ? `${state}, ${country}` : country;
  const effectiveDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `TERMS OF SERVICE

Effective Date: ${effectiveDate}

1. ACCEPTANCE OF TERMS

By accessing and using ${businessName} (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this Service.

These Terms of Service ("Terms") constitute a legally binding agreement between you and ${businessName} ("we," "our," or "us"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.

2. DESCRIPTION OF SERVICE

${businessName} provides ${data.websiteType || 'online services'} through our website and related platforms. We reserve the right to modify, suspend, or discontinue any aspect of the Service at any time, with or without notice.

2.1 Digital Document Purchase

When you purchase digital documents (such as privacy policies, terms of service, or cookie policies) through our Service, you are purchasing a license to use the generated documents for your business purposes. The documents are provided as digital files that you can download, modify, and use in accordance with these Terms.

2.2 No Legal Advice

The documents generated by our Service are templates and do not constitute legal advice. We are not a law firm, and our Service does not provide legal services. The documents are provided "as is" for informational purposes only. You should consult with a qualified legal professional to ensure the documents meet your specific legal requirements and business needs.

2.3 Limitation of Reliance

You acknowledge and agree that:
- The documents generated are general templates and may not be suitable for your specific circumstances
- You are solely responsible for reviewing, customizing, and ensuring the legal adequacy of any documents you use
- We are not liable for any legal consequences arising from your use of the generated documents
- You should have documents reviewed by a qualified attorney before using them in any legal context

3. USE LICENSE

3.1 Permission to Use

Permission is granted to temporarily access the materials on ${businessName} for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.

3.2 Restrictions

Under this license, you may not:
- Modify or copy the materials
- Use the materials for any commercial purpose or for any public display (commercial or non-commercial)
- Attempt to decompile or reverse engineer any software contained on ${businessName}
- Remove any copyright or other proprietary notations from the materials
- Transfer the materials to another person or "mirror" the materials on any other server

This license shall automatically terminate if you violate any of these restrictions and may be terminated by ${businessName} at any time.

4. USER ACCOUNTS AND REGISTRATION

4.1 Account Creation

Some features of the Service may require you to create an account. When you create an account, you agree to:
- Provide accurate, current, and complete information
- Maintain and promptly update your account information
- Maintain the security of your password and identification
- Accept all responsibility for activities that occur under your account
- Notify us immediately of any unauthorized use of your account

4.2 Account Termination

We reserve the right to suspend or terminate your account and access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties, or for any other reason.

5. USER CONDUCT

You agree not to use the Service to:
- Violate any applicable laws or regulations
- Infringe upon the rights of others
- Transmit any harmful, offensive, or illegal content
- Interfere with or disrupt the Service or servers
- Attempt to gain unauthorized access to any portion of the Service
- Collect or store personal data about other users without their consent
- Use automated systems (bots, scrapers) to access the Service without permission

6. INTELLECTUAL PROPERTY

6.1 Ownership

All content, features, and functionality of the Service, including but not limited to text, graphics, logos, icons, images, audio clips, digital downloads, and software, are the exclusive property of ${businessName} or its content suppliers and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.

6.2 Limited License

Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your personal, non-commercial use.

7. DISCLAIMER

THE MATERIALS ON ${businessName.toUpperCase()} ARE PROVIDED ON AN 'AS IS' BASIS. ${businessName.toUpperCase()} MAKES NO WARRANTIES, EXPRESSED OR IMPLIED, AND HEREBY DISCLAIMS AND NEGATES ALL OTHER WARRANTIES INCLUDING, WITHOUT LIMITATION:

- IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY
- FITNESS FOR A PARTICULAR PURPOSE
- NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR OTHER VIOLATION OF RIGHTS
- ACCURACY, RELIABILITY, OR COMPLETENESS OF CONTENT
- UNINTERRUPTED OR ERROR-FREE OPERATION

Further, ${businessName} does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.

8. LIMITATIONS OF LIABILITY

IN NO EVENT SHALL ${businessName.toUpperCase()} OR ITS SUPPLIERS, AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF DATA OR PROFIT, OR DUE TO BUSINESS INTERRUPTION) ARISING OUT OF THE USE OR INABILITY TO USE THE MATERIALS ON ${businessName.toUpperCase()}, EVEN IF ${businessName} OR AN AUTHORIZED REPRESENTATIVE HAS BEEN NOTIFIED ORALLY OR IN WRITING OF THE POSSIBILITY OF SUCH DAMAGE.

Some jurisdictions do not allow limitations on implied warranties or limitations of liability for incidental or consequential damages, so these limitations may not apply to you.

9. INDEMNIFICATION

You agree to indemnify, defend, and hold harmless ${businessName}, its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from:

- Your use of and access to the Service
- Your violation of any term of these Terms
- Your violation of any third-party right, including without limitation any copyright, property, or privacy right
- Any claim that your use of the Service caused damage to a third party

10. ACCURACY OF MATERIALS

The materials appearing on ${businessName} could include technical, typographical, or photographic errors. ${businessName} does not warrant that any of the materials on its website are accurate, complete, or current. ${businessName} may make changes to the materials contained on its website at any time without notice. However, ${businessName} does not make any commitment to update the materials.

11. LINKS TO THIRD-PARTY SITES

${businessName} has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by ${businessName} of the site. Use of any such linked website is at the user's own risk.

12. MODIFICATIONS TO TERMS

${businessName} may revise these Terms of Service at any time without notice. By using this Service, you are agreeing to be bound by the then current version of these Terms of Service.

We will notify you of any material changes by:
- Posting the new Terms of Service on this page
- Updating the "Effective Date" at the top
- Providing notice through the Service (if applicable)

Your continued use of the Service after any changes constitutes your acceptance of the new Terms.

13. TERMINATION

We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.

Upon termination, your right to use the Service will immediately cease. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.

14. GOVERNING LAW AND JURISDICTION

These Terms and Conditions are governed by and construed in accordance with the laws of ${location}, without regard to its conflict of law provisions.

You irrevocably submit to the exclusive jurisdiction of the courts in ${location} for the resolution of any disputes arising out of or relating to these Terms or the Service.

15. SEVERABILITY

If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect and enforceable.

16. ENTIRE AGREEMENT

These Terms constitute the entire agreement between you and ${businessName} regarding the use of the Service and supersede all prior or contemporaneous communications, proposals, and agreements, whether oral or written, between you and ${businessName}.

17. WAIVER

No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and ${businessName}'s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.

18. REFUND POLICY

18.1 Digital Products

Due to the digital nature of our products (generated documents), all sales are final. We do not offer refunds for digital document purchases once the documents have been generated and made available for download.

18.2 Exceptions

Refunds may be considered only in the following circumstances:
- Technical failure preventing you from accessing or downloading your purchased documents
- Duplicate charges due to processing errors
- Document generation failure that we are unable to resolve

To request a refund, please contact us at ${contactEmail} within 7 days of your purchase with details of the issue. Refund decisions are at our sole discretion.

19. CONTACT INFORMATION

If you have any questions about these Terms of Service, please contact us:

Email: ${contactEmail}
Location: ${location}

20. DISCLAIMER

These Terms of Service are provided as a general template and do not constitute legal advice. While we have made efforts to ensure these terms are comprehensive, you should consult with a qualified legal professional to ensure these terms meet your specific legal requirements and business needs.

The information in these Terms is provided "as is" without warranty of any kind, express or implied. We are not responsible for any legal consequences that may arise from the use of these Terms.`;
}
