"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function PreviewPage() {
  const [activeTab, setActiveTab] = useState("privacy");
  const [policyData, setPolicyData] = useState<any>(null);
  const [isPaid, setIsPaid] = useState(false);

  useEffect(() => {
    // Get policy data from localStorage or API
    const stored = localStorage.getItem("policyData");
    if (stored) {
      setPolicyData(JSON.parse(stored));
    }
  }, []);

  const handleCopy = async () => {
    const text = getCurrentPolicyText();
    try {
      await navigator.clipboard.writeText(text);
      alert("Copied to clipboard!");
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownload = () => {
    const text = getCurrentPolicyText();
    const filename = activeTab === "privacy" ? "privacy-policy.txt" 
                   : activeTab === "terms" ? "terms-of-service.txt"
                   : "cookie-policy.txt";
    
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getCurrentPolicyText = () => {
    if (!policyData) return "";
    // This would normally come from API
    return "Privacy Policy content would be generated here...";
  };

  return (
    <main className="min-h-screen py-20 px-4">
      <div className="max-w-4xl mx-auto">
        <Card>
          <CardHeader>
            <CardTitle className="text-3xl mb-2">Preview Your Policy</CardTitle>
            <CardDescription>
              Review your generated privacy policy and related documents
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="privacy">Privacy Policy</TabsTrigger>
                <TabsTrigger value="terms" disabled={!isPaid}>
                  Terms of Service {!isPaid && "(Premium)"}
                </TabsTrigger>
                <TabsTrigger value="cookies" disabled={!isPaid}>
                  Cookie Policy {!isPaid && "(Premium)"}
                </TabsTrigger>
              </TabsList>
              
              <TabsContent value="privacy" className="mt-6">
                <div className="prose max-w-none mb-6 p-4 border rounded">
                  <pre className="whitespace-pre-wrap font-sans">
                    {getCurrentPolicyText()}
                  </pre>
                  {!isPaid && (
                    <div className="mt-4 pt-4 border-t text-center text-sm text-gray-500">
                      Generated by PolicyDraft.in - Create yours free
                    </div>
                  )}
                </div>
                <div className="flex gap-4">
                  <Button onClick={handleCopy}>Copy</Button>
                  <Button onClick={handleDownload} variant="outline">Download as Text</Button>
                </div>
              </TabsContent>

              <TabsContent value="terms" className="mt-6">
                <div className="prose max-w-none mb-6 p-4 border rounded">
                  <pre className="whitespace-pre-wrap font-sans">
                    Terms of Service content...
                  </pre>
                </div>
                <div className="flex gap-4">
                  <Button onClick={handleCopy}>Copy</Button>
                  <Button onClick={handleDownload} variant="outline">Download as Text</Button>
                </div>
              </TabsContent>

              <TabsContent value="cookies" className="mt-6">
                <div className="prose max-w-none mb-6 p-4 border rounded">
                  <pre className="whitespace-pre-wrap font-sans">
                    Cookie Policy content...
                  </pre>
                </div>
                <div className="flex gap-4">
                  <Button onClick={handleCopy}>Copy</Button>
                  <Button onClick={handleDownload} variant="outline">Download as Text</Button>
                </div>
              </TabsContent>
            </Tabs>

            {!isPaid && (
              <Card className="mt-6 border-primary">
                <CardHeader>
                  <CardTitle>Upgrade to Premium</CardTitle>
                  <CardDescription>
                    Unlock all features for just ₹999 one-time
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <ul className="list-disc list-inside mb-4 space-y-2">
                    <li>Remove watermark</li>
                    <li>Get Terms of Service</li>
                    <li>Get Cookie Policy</li>
                    <li>Download as PDF</li>
                  </ul>
                  <Button className="w-full">Pay Now - ₹999</Button>
                </CardContent>
              </Card>
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
